"""rui11th

Revision ID: b83c1c923e37
Revises: 05c6c8d13c50
Create Date: 2019-12-23 23:10:39.645697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83c1c923e37'
down_revision = '05c6c8d13c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokenn', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_user_tokenn'), 'user', ['tokenn'], unique=True)
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=True)
    op.drop_index(op.f('ix_user_tokenn'), table_name='user')
    op.drop_column('user', 'tokenn')
    # ### end Alembic commands ###
