"""added secret key to user

Revision ID: d3d1092f39f5
Revises: 99358c0389cb
Create Date: 2020-01-20 07:35:35.645077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d1092f39f5'
down_revision = '99358c0389cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['secret_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secret_key')
    # ### end Alembic commands ###
