"""empty message

Revision ID: ddca04196ec8
Revises: eb7216510d90
Create Date: 2020-01-20 09:37:50.415279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddca04196ec8'
down_revision = 'eb7216510d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('campus', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'image')
    op.drop_column('users', 'campus')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
