runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

resources:
  memory_gb: 4
  disk_size_gb: 10
  cpu: 1
manual_scaling:
  instances: 1

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:asint2019@/secretariats?host=/cloudsql/asint2-262123:europe-west2:asint-secretariat

# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: asint2-262123:europe-west2:asint-secretariat