"""secretariats table

Revision ID: 696ee81927ed
Revises: 
Create Date: 2019-12-12 08:47:33.944846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696ee81927ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretariat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secretariat_name'), 'secretariat', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secretariat_name'), table_name='secretariat')
    op.drop_table('secretariat')
    # ### end Alembic commands ###
