"""secretariats changed

Revision ID: a0e07e7dcb1b
Revises: 696ee81927ed
Create Date: 2019-12-12 12:51:55.639838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e07e7dcb1b'
down_revision = '696ee81927ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secretariat', sa.Column('description', sa.String(length=300), nullable=True))
    op.add_column('secretariat', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('secretariat', sa.Column('opening_hours', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_secretariat_location'), 'secretariat', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secretariat_location'), table_name='secretariat')
    op.drop_column('secretariat', 'opening_hours')
    op.drop_column('secretariat', 'location')
    op.drop_column('secretariat', 'description')
    # ### end Alembic commands ###
