runtime: python
env: flex
entrypoint: gunicorn -b :8080 main:app

runtime_config:
  python_version: 3

resources:
  memory_gb: 4
  disk_size_gb: 10
  cpu: 1
manual_scaling:
  instances: 1

env_variables:
  IS_APPENGINE: 'true'
  WS_AUTH: 'password-asint'

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
  env_variables:
  CLOUD_SQL_USERNAME: "root"
  CLOUD_SQL_PASSWORD: "1995jose"
  CLOUD_SQL_DATABASE_NAME: "cache"
  CLOUD_SQL_CONNECTION_NAME: "asint2-262123:europe-west6:memcached
